### ISSUE TITLE
Imported schemas do not validate examples

### ISSUE THREAD

**Issue by awlayton** [OADA/formats#3]
Several of the schemas from the dev branch of oada-formats do not validate their own examples.

As I am not familiar with those formats, I do not know what to change to remedy most of them. A few were obvious typos (see ab830ea43af580559aac2b3ed07420736a7ead6c) but the following errors remain:

```
  1) Type Schemas
       /oada/as-harvested/yield-moisture-dataset/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.data['kdjf02ijk3f'].location.latitude should be string, data.data['kdjf02ijk3f'].location.longitude should be string, data.data['0f2jflk2j3l'].location.latitude should be string, data.data['0f2jflk2j3l'].location.longitude should be st ring, data._rev should be integer, data.indexing[0].source should be equal to one of the allowed values, data.indexing[0].index should be equal to one of the allowed values, data.indexing[0].index should be equal to one of the allowed value s, data.indexing[0].value should match pattern "^geohash-[1-9][0-9]*$", data.indexing[0].index should be equal to one of the allowed values, data.indexing[0] should match some schema in anyOf, data.indexing[2].index should be equal to one o f the allowed values, data.indexing[2].source should be equal to one of the allowed values, data.indexing[2].value should match pattern "^[0-9]{4}$", data.indexing[2].index should be equal to one of the allowed values, data.indexing[2].valu e should match pattern "^geohash-[1-9][0-9]*$", data.indexing[2].index should be equal to one of the allowed values, data.indexing[2] should match some schema in anyOf
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  2) Type Schemas
       /oada/tiled-maps/dry-yield-map/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.indexing[2].index should be equal to one of the allowed values, data.indexing[2].source should be equal to one of the allowed values, data.indexing[2].value should match pattern "^[0-9]{4}$", data.indexing[2].index should be equal to o ne of the allowed values, data.indexing[2].value should match pattern "^geohash-[1-9][0-9]*$", data.indexing[2].index should be equal to one of the allowed values, data.indexing[2] should match some schema in anyOf
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  3) Type Schemas
       /oada/tiled-maps/moisture-map/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.indexing[2].index should be equal to one of the allowed values, data.indexing[2].source should be equal to one of the allowed values, data.indexing[2].value should match pattern "^[0-9]{4}$", data.indexing[2].index should be equal to o ne of the allowed values, data.indexing[2].value should match pattern "^geohash-[1-9][0-9]*$", data.indexing[2].index should be equal to one of the allowed values, data.indexing[2] should match some schema in anyOf
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  4) Type Schemas
       /trellis/audit/generic/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.certificationid.id_source should be object, data.organization.organizationid.id_source should be object, data.sections[0].score.possible should be string, data.control_points['1.01.01'].score.possible should be string, data.control_poi nts['1.01.01'].score.compliance should be string, data.control_points['1.01.02'].score.possible should be string, data.control_points['1.01.02'].score.compliance should be string, data.control_points['1.01.03'].score.possible should be stri ng, data.control_points['1.01.03'].score.compliance should be string, data.control_points['2.11.02'].score.possible should be string, data.control_points['2.11.02'].score.compliance should be string, data.control_points['2.11.02a'].score.po ssible should be string, data.control_points['2.11.02a'].score.compliance should be string
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  5) Type Schemas
       /trellis/audit/globalgap/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.scheme.name should be equal to one of the allowed values, data.organization should have required property 'otherids', data.organization.organizationid.id_source should be object, data.conditions_during_audit should have required proper ty 'FSMS_observed_date', data.conditions_during_audit.operation_observed_date should be object, data.certificationid.id_source should be object, data.control_points['AF 1.1.1'].globalgap_level should be object, data.control_points['AF 1.1.1 '].globalgap_level should be object, data.control_points['AF 1.1.1'].globalgap_level should match some schema in anyOf
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  6) Type Schemas
       /trellis/certificate/generic/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.certifying_body should have required property 'auditor', data.organization.organizationid.id_source should be object, data.certificate_validity_period should be string, data.certificationid.id_source should be object
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  7) Type Schemas
       /trellis/certificate/primusgfs/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.organization.organizationid.id_source should be object, data.certificate_validity_period should be string, data.certificationid.id_source should be object
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)

  8) Type Schemas
       /trellis/corrective-actions/primusgfs/v1.schema.json
         should have valid examples:
     AssertionError: expected data to match json-schema
data.organization should have required property 'organizationid', data.scope should have required property 'products_observed', data.sections[0].score.possible should be string, data.sections[1].score.possible should be string, data.control _points['1.01.03'].score.preliminary.possible should be string, data.control_points['1.03.03'].score.preliminary.possible should be string, data.control_points['1.05.05'].score.preliminary.possible should be string, data.control_points['1.0 6.01'].score.preliminary.possible should be string, data.control_points['1.06.03'].score.preliminary.possible should be string, data.control_points['1.08.02'].score.preliminary.possible should be string
      at Context.<anonymous> (src/schemas.spec.ts:85:33)
      at processImmediate (internal/timers.js:456:21)
```

Someone who knows these formats should probably fix them... (maybe @aultac or @sanoel?)

**Comment by aultac** [comment]
I will try to get these fixed up if I get a Saturday in the near future when it's raining so no planting happens.
